version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: web_app_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5433"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    environment:
      DB_HOST: db
      DB_NAME: web_app_development
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "3000:3000"
    depends_on:
      - db
